// Package storage provides a Supabase Storage client for persisting
// media (images, videos) generated by the solana-clawd daemon.
package storage

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path"
	"strings"
	"time"
)

// SupabaseStorage uploads files to a Supabase Storage bucket.
type SupabaseStorage struct {
	baseURL    string // e.g. https://xxx.supabase.co
	serviceKey string // service_role JWT
	bucket     string // bucket name
	httpClient *http.Client
}

// NewSupabaseStorage creates a client from environment variables.
func NewSupabaseStorage() *SupabaseStorage {
	baseURL := strings.TrimRight(os.Getenv("SUPABASE_URL"), "/")
	serviceKey := os.Getenv("SUPABASE_SERVICE_ROLE")
	bucket := os.Getenv("SUPABASE_STORAGE_BUCKET")
	if baseURL == "" || serviceKey == "" {
		return nil
	}
	if bucket == "" {
		bucket = "media"
	}
	log.Printf("[STORAGE] 📦 Supabase storage initialized (bucket: %s)", bucket)
	return &SupabaseStorage{
		baseURL:    baseURL,
		serviceKey: serviceKey,
		bucket:     bucket,
		httpClient: &http.Client{Timeout: 60 * time.Second},
	}
}

// IsConfigured returns true if Supabase storage is available.
func (s *SupabaseStorage) IsConfigured() bool {
	return s != nil && s.baseURL != "" && s.serviceKey != ""
}

// UploadFromURL downloads a file from a URL and uploads it to Supabase Storage.
// Returns the public URL of the stored file.
func (s *SupabaseStorage) UploadFromURL(ctx context.Context, sourceURL, folder, filename string) (string, error) {
	// Download the file
	req, err := http.NewRequestWithContext(ctx, "GET", sourceURL, nil)
	if err != nil {
		return "", fmt.Errorf("storage: create download request: %w", err)
	}
	resp, err := s.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("storage: download failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != 200 {
		return "", fmt.Errorf("storage: download HTTP %d", resp.StatusCode)
	}

	data, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", fmt.Errorf("storage: read body: %w", err)
	}

	contentType := resp.Header.Get("Content-Type")
	if contentType == "" {
		contentType = detectContentType(filename, data)
	}

	return s.Upload(ctx, data, contentType, folder, filename)
}

// Upload stores raw bytes in Supabase Storage. Returns the public URL.
func (s *SupabaseStorage) Upload(ctx context.Context, data []byte, contentType, folder, filename string) (string, error) {
	objectPath := path.Join(folder, filename)
	uploadURL := fmt.Sprintf("%s/storage/v1/object/%s/%s", s.baseURL, s.bucket, objectPath)

	req, err := http.NewRequestWithContext(ctx, "POST", uploadURL, bytes.NewReader(data))
	if err != nil {
		return "", fmt.Errorf("storage: create request: %w", err)
	}
	req.Header.Set("Authorization", "Bearer "+s.serviceKey)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("x-upsert", "true")

	resp, err := s.httpClient.Do(req)
	if err != nil {
		return "", fmt.Errorf("storage: upload failed: %w", err)
	}
	defer resp.Body.Close()

	body, _ := io.ReadAll(resp.Body)
	if resp.StatusCode != 200 && resp.StatusCode != 201 {
		return "", fmt.Errorf("storage: upload HTTP %d: %s", resp.StatusCode, string(body))
	}

	publicURL := fmt.Sprintf("%s/storage/v1/object/public/%s/%s", s.baseURL, s.bucket, objectPath)
	log.Printf("[STORAGE] ✅ Uploaded %s (%d bytes)", objectPath, len(data))
	return publicURL, nil
}

// PublicURL returns the public URL for an object in the bucket.
func (s *SupabaseStorage) PublicURL(objectPath string) string {
	return fmt.Sprintf("%s/storage/v1/object/public/%s/%s", s.baseURL, s.bucket, objectPath)
}

func detectContentType(filename string, data []byte) string {
	ext := strings.ToLower(path.Ext(filename))
	switch ext {
	case ".png":
		return "image/png"
	case ".jpg", ".jpeg":
		return "image/jpeg"
	case ".gif":
		return "image/gif"
	case ".webp":
		return "image/webp"
	case ".mp4":
		return "video/mp4"
	case ".webm":
		return "video/webm"
	default:
		return http.DetectContentType(data)
	}
}
