#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
#  OpenClawd — One-Shot Installer
#  Installs: Chrome Extension + Page Agent + MCP Bridge
#  Connects to: OpenClawd orchestrator, SolanaOS daemon
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
EXT_DIR="$REPO_ROOT/chrome-extension"
MCP_DIR="$REPO_ROOT/openclawd-stack/orchestrator"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color
BOLD='\033[1m'

echo -e "${PURPLE}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║                                                              ║"
echo "║   🦞  O P E N C L A W D  —  pAGENT Browser Agent            ║"
echo "║                                                              ║"
echo "║   The Hermes of Web3 • AI Agent Browser                      ║"
echo "║                                                              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Step 1: Check prerequisites ──────────────────────────────────
echo -e "\n${BOLD}🔍 Checking prerequisites...${NC}"

check_command() {
  if command -v "$1" &> /dev/null; then
    echo -e "  ${GREEN}✓${NC} $1 found"
    return 0
  else
    echo -e "  ${YELLOW}⚠${NC} $1 not found (optional)"
    return 1
  fi
}

check_command "node"
check_command "npm"
check_command "git"

# ── Step 2: Build Chrome Extension ────────────────────────────────
echo -e "\n${BOLD}🔨 Building Chrome Extension...${NC}"

cd "$EXT_DIR" || exit 1

# Create build directory
mkdir -p build
rm -rf build/*

# Copy essential files
echo -e "  ${BLUE}→${NC} Copying extension files..."
cp manifest.json build/
cp popup.html build/
cp popup.css build/
cp popup.js build/
cp background.js build/

# Copy icons
mkdir -p build/icons
cp -r icons/*.png build/icons/ 2>/dev/null || true

# Copy clawd-agent (page agent)
cp -r clawd-agent build/

echo -e "  ${GREEN}✓${NC} Extension built at: $EXT_DIR/build/"

# ── Step 3: Start OpenClawd Orchestrator MCP ────────────────────
echo -e "\n${BOLD}🚀 Starting OpenClawd MCP Bridge...${NC}"

cd "$MCP_DIR" || exit 1

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
  echo -e "  ${YELLOW}⚠${NC} Installing orchestrator dependencies..."
  npm install
fi

# Start MCP server in background
echo -e "  ${BLUE}→${NC} Starting MCP bridge on port 3001..."
nohup node dist/index.js > .logs/mcp-bridge.log 2>&1 &
MCP_PID=$!
echo $MCP_PID > .mcp-bridge.pid

# Wait for MCP to be ready
sleep 2

if kill -0 $MCP_PID 2>/dev/null; then
  echo -e "  ${GREEN}✓${NC} MCP bridge running (PID: $MCP_PID)"
else
  echo -e "  ${YELLOW}⚠${NC} MCP bridge failed to start - check logs"
fi

# ── Step 4: Generate Chrome Extension Config ─────────────────────
echo -e "\n${BOLD}⚙️  Generating extension config...${NC}"

cat > "$EXT_DIR/build/openclawd-config.js" << 'EOFCONFIG'
// OpenClawd Extension Configuration
// Auto-generated by one-shot installer

const OPENCLAWD_CONFIG = {
  version: '3.0.0',
  
  // MCP Bridge (OpenClawd orchestrator)
  mcpBridge: {
    port: 3001,
    url: 'http://localhost:3001',
  },
  
  // Gateway (SolanaOS daemon)
  gateway: {
    default: 'http://127.0.0.1:18790',
    candidates: [
      'http://127.0.0.1:18790',
      'http://127.0.0.1:7777',
      'http://localhost:18790',
      'http://localhost:7777',
    ],
  },
  
  // Wallet API (agent-wallet service)
  walletApi: {
    port: 8421,
    url: 'http://localhost:8421',
  },
  
  // MawdAxe Mining Fleet
  mawdaxe: {
    port: 8420,
    url: 'http://localhost:8420',
  },
  
  // LLM Providers
  llm: {
    defaultProvider: 'openrouter',
    defaultModel: 'anthropic/claude-sonnet-4-6',
    providers: ['openrouter', 'anthropic', 'xai', 'ollama'],
  },
  
  // Agent Harness Integration
  harness: {
    enabled: true,
    catalogUrl: 'https://hub.solanaclawd.com',
    agentsPath: '/agents',
    skillsPath: '/skills',
  },
  
  // SolanaOS Binary Connection
  solanaos: {
    binaryPath: 'solanaos',
    configPath: '~/.solanaos/solanaos.json',
    gatewayPort: 18790,
    controlUIPort: 7777,
  },
  
  // $CLAWD Token (tier gating)
  clawdToken: {
    mint: '8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump',
    pumpFunUrl: 'https://pump.fun/8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump',
  },
  
  // OpenClawd Links
  links: {
    hub: 'https://hub.solanaclawd.com',
    website: 'https://solanaclawd.com',
    docs: 'https://docs.solanaclawd.com',
    github: 'https://github.com/x402agent/openclawd',
  },
};

if (typeof window !== 'undefined') {
  window.OPENCLAWD_CONFIG = OPENCLAWD_CONFIG;
}
EOFCONFIG

echo -e "  ${GREEN}✓${NC} Config generated"

# ── Step 5: Create Claude Desktop Config ──────────────────────────
echo -e "\n${BOLD}📝 Creating Claude Desktop MCP config...${NC}"

CLAUDE_CONFIG_DIR="$HOME/Library/Application Support/Claude"
mkdir -p "$CLAUDE_CONFIG_DIR"

cat > "$CLAUDE_CONFIG_DIR/claude_desktop_config.json" << 'EOFCLAUDE'
{
  "mcpServers": {
    "openclawd": {
      "command": "node",
      "args": ["/Users/8bit/openclawd/openclawd-stack/orchestrator/dist/index.js"],
      "env": {
        "OPENCLAWD_GATEWAY_URL": "http://localhost:18790",
        "OPENCLAWD_MCP_PORT": "3001"
      }
    },
    "openclawd-browser": {
      "command": "node",
      "args": ["/Users/8bit/openclawd/chrome-extension/mcp/src/index.js"],
      "env": {
        "LLM_BASE_URL": "https://api.openrouter.ai/v1",
        "LLM_MODEL_NAME": "anthropic/claude-sonnet-4-6"
      }
    }
  }
}
EOFCLAUDE

echo -e "  ${GREEN}✓${NC} Claude Desktop config created"

# ── Step 6: Print Instructions ────────────────────────────────────
echo -e "\n${PURPLE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}${GREEN}✅ Installation Complete!${NC}"
echo -e "${PURPLE}═══════════════════════════════════════════════════════════════${NC}"

echo -e "\n${BOLD}📦 Extension Location:${NC}"
echo -e "  ${BLUE}→${NC} Load unpacked: $EXT_DIR/build/"
echo -e "  ${BLUE}→${NC} Load pAGENT: $EXT_DIR/build/clawd-agent/"

echo -e "\n${BOLD}🔧 How to Install Extension:${NC}"
echo -e "  1. Open chrome://extensions/"
echo -e "  2. Enable Developer mode (top-right toggle)"
echo -e "  3. Click 'Load unpacked'"
echo -e "  4. Select: $EXT_DIR/build/"
echo -e "  5. Click the 🦞 icon in your toolbar"

echo -e "\n${BOLD}🦞 For Full pAGENT (GUI Vision):${NC}"
echo -e "  1. Open chrome://extensions/"
echo -e "  2. Remove current extension"
echo -e "  3. Click 'Load unpacked'"
echo -e "  4. Select: $EXT_DIR/build/clawd-agent/"
echo -e "  5. Open side panel for browser automation"

echo -e "\n${BOLD}🤖 Claude Desktop Integration:${NC}"
echo -e "  Config written to: $CLAUDE_CONFIG_DIR/claude_desktop_config.json"
echo -e "  Restart Claude Desktop to activate MCP servers"

echo -e "\n${BOLD}🌐 OpenClawd Services Running:${NC}"
echo -e "  ${GREEN}✓${NC} MCP Bridge: http://localhost:3001 (PID: $MCP_PID)"
echo -e "  ${YELLOW}○${NC} Gateway: Connect to SolanaOS at :18790"
echo -e "  ${YELLOW}○${NC} Wallet API: Start with 'npm run ext:vault'"

echo -e "\n${BOLD}📚 Documentation:${NC}"
echo -e "  ${BLUE}→${NC} Hub: https://hub.solanaclawd.com"
echo -e "  ${BLUE}→${NC} Docs: https://docs.solanaclawd.com"
echo -e "  ${BLUE}→${NC} GitHub: https://github.com/x402agent/openclawd"

echo -e "\n${BOLD}💰 $CLAWD Token:${NC}"
echo -e "  Mint: 8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump"
echo -e "  Buy: https://pump.fun/8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump"
echo -e "  Hold $CLAWD to unlock Pro features in the extension"

echo -e "\n${PURPLE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BOLD}The Hermes of Web3 🦞 — Your keys, your agent, your rules.${NC}"
echo -e "${PURPLE}═══════════════════════════════════════════════════════════════${NC}"