// AUTO-GENERATED from /install.sh — do not edit by hand.
// Regenerate with: npm run sync (in workers/install-worker).
export const INSTALL_SCRIPT = `#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────
#  openclawd one-shot installer
#  Hosted at: https://solanaclawd.com/install.sh
#  Usage:     curl -fsSL https://solanaclawd.com/install.sh | bash
# ─────────────────────────────────────────────────────────────
#
#  What it does:
#   1. Verifies node >= 18, git, npm.
#   2. Installs the public \`solana-clawd\` CLI globally from npm.
#   3. Writes a scaffolded ~/.openclawd/.env with sensible defaults.
#   4. Prints the pair/mint/status next steps.
#
#  This installer is self-contained — it does NOT require access to
#  the openclawd monorepo (which may be private). To get the full
#  monorepo, run:
#     gh repo clone x402agent/openclawd ~/.openclawd
#
# ─────────────────────────────────────────────────────────────
set -euo pipefail

TARGET_DIR="\${OPENCLAWD_DIR:-$HOME/.openclawd}"
SOLANA_CLAWD_BASE_URL="\${SOLANA_CLAWD_BASE_URL:-https://solanaclawd.com}"

c_reset=$'\\033[0m'; c_bold=$'\\033[1m'; c_green=$'\\033[32m'; c_cyan=$'\\033[36m'; c_yellow=$'\\033[33m'; c_red=$'\\033[31m'
log()  { printf "%s▸%s %s\\n" "$c_cyan"   "$c_reset" "$*"; }
ok()   { printf "%s✓%s %s\\n" "$c_green"  "$c_reset" "$*"; }
warn() { printf "%s!%s %s\\n" "$c_yellow" "$c_reset" "$*"; }
die()  { printf "%s✗%s %s\\n" "$c_red"    "$c_reset" "$*" >&2; exit 1; }

cat <<'BANNER'
   ____                   ___  _                _
  / __ \\ ___  ___  ___   / _ \\/ /__ ____    ____/ /
 / /_/ // _ \\/ -_)/ _ \\ / ___/ / _ \`/\\ \\/\\ / /_  _/
 \\____// .__/\\__// //_//_/  /_/\\_,_//_/\\_\\/  /_/
      /_/                openclawd · solana-clawd stack
BANNER

log "Connecting to $SOLANA_CLAWD_BASE_URL"

need() { command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"; }
need curl
need node
need npm

NODE_MAJOR="$(node -p 'process.versions.node.split(".")[0]')"
[ "$NODE_MAJOR" -ge 18 ] || die "node >= 18 required (have $(node -v))"

# 1. install the solana-clawd CLI globally from public npm
log "Installing solana-clawd CLI from npm…"
if npm i -g solana-clawd >/dev/null 2>&1; then
  ok "solana-clawd $(solana-clawd --version 2>/dev/null || echo installed)"
else
  warn "global npm install failed — retrying with sudo"
  sudo npm i -g solana-clawd
  ok "solana-clawd installed (sudo)"
fi

# 2. scaffold ~/.openclawd/.env
mkdir -p "$TARGET_DIR"
ENV_FILE="$TARGET_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  warn "$ENV_FILE already exists — leaving untouched"
else
  cat > "$ENV_FILE" <<EOF
# openclawd — generated by solanaclawd.com/install.sh
# Fill in your provider keys before running agents.

# ── Solana / base URLs ──────────────────────────────
SOLANA_CLAWD_BASE_URL=$SOLANA_CLAWD_BASE_URL
CLAWD_MINT=8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump
SOLANA_RPC_URL=https://api.mainnet-beta.solana.com
HELIUS_API_KEY=
HELIUS_RPC_URL=

# ── Model router ────────────────────────────────────
OPENROUTER_API_KEY=
CLAWDROUTER_DEFAULT_REASONING=xai/grok-4.20-beta
CLAWDROUTER_DEFAULT_LONGCTX=moonshot/kimi-k2.6

# ── Direct providers (optional) ─────────────────────
XAI_API_KEY=
ANTHROPIC_API_KEY=
OPENAI_API_KEY=
MOONSHOT_API_KEY=

# ── Runtime / infra (optional) ──────────────────────
E2B_API_KEY=
PRIVY_APP_ID=
PRIVY_APP_SECRET=
TELEGRAM_BOT_TOKEN=
TAILSCALE_AUTH_KEY=
EOF
  ok "Created $ENV_FILE — fill in your provider keys"
fi

# 3. print next steps
cat <<EOF

\${c_bold}Next steps\${c_reset}
  1. Edit your env:      \${c_cyan}\\$EDITOR $ENV_FILE\${c_reset}
  2. Pair this device:   \${c_cyan}solana-clawd pair <CODE>\${c_reset}
  3. Mint your agent:    \${c_cyan}solana-clawd mint\${c_reset}
  4. Check status:       \${c_cyan}solana-clawd status\${c_reset}

Optional — clone the full monorepo (requires repo access):
  \${c_cyan}gh repo clone x402agent/openclawd $TARGET_DIR/repo\${c_reset}

Docs & website: $SOLANA_CLAWD_BASE_URL
EOF
ok "openclawd installed."
`;
